apiVersion: v1
kind: Service
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  type: NodePort
  selector:
    app: zomato
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
