apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  replicas: 4
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: zomato
          image: somemahesh/zomato-app:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
